// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rhobi
double rhobi(double z, double k);
RcppExport SEXP _sparseshootS_rhobi(SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rhobi(z, k));
    return rcpp_result_gen;
END_RCPP
}
// scaleC
double scaleC(arma::vec u, double kp, double cc, double initialsc, int maxit, double tol);
RcppExport SEXP _sparseshootS_scaleC(SEXP uSEXP, SEXP kpSEXP, SEXP ccSEXP, SEXP initialscSEXP, SEXP maxitSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< double >::type kp(kpSEXP);
    Rcpp::traits::input_parameter< double >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< double >::type initialsc(initialscSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleC(u, kp, cc, initialsc, maxit, tol));
    return rcpp_result_gen;
END_RCPP
}
// wbi
double wbi(double z, double k);
RcppExport SEXP _sparseshootS_wbi(SEXP zSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(wbi(z, k));
    return rcpp_result_gen;
END_RCPP
}
// sign
double sign(double x);
RcppExport SEXP _sparseshootS_sign(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(sign(x));
    return rcpp_result_gen;
END_RCPP
}
// betawls
arma::mat betawls(arma::mat X, arma::mat Y, arma::mat W);
RcppExport SEXP _sparseshootS_betawls(SEXP XSEXP, SEXP YSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(betawls(X, Y, W));
    return rcpp_result_gen;
END_RCPP
}
// univest
List univest(arma::mat x, arma::mat y, double k, arma::vec wt, double delta, int maxiter, double tol, arma::vec prevresiduals, double tolscale, int maxitscale, double sinit);
RcppExport SEXP _sparseshootS_univest(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP wtSEXP, SEXP deltaSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP prevresidualsSEXP, SEXP tolscaleSEXP, SEXP maxitscaleSEXP, SEXP sinitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prevresiduals(prevresidualsSEXP);
    Rcpp::traits::input_parameter< double >::type tolscale(tolscaleSEXP);
    Rcpp::traits::input_parameter< int >::type maxitscale(maxitscaleSEXP);
    Rcpp::traits::input_parameter< double >::type sinit(sinitSEXP);
    rcpp_result_gen = Rcpp::wrap(univest(x, y, k, wt, delta, maxiter, tol, prevresiduals, tolscale, maxitscale, sinit));
    return rcpp_result_gen;
END_RCPP
}
// univest_sparse
List univest_sparse(arma::mat x, arma::mat y, double k, arma::vec wt, double delta, int maxiter, double tol, arma::vec prevresiduals, double tolscale, int maxitscale, double lambda, int post, double sinit);
RcppExport SEXP _sparseshootS_univest_sparse(SEXP xSEXP, SEXP ySEXP, SEXP kSEXP, SEXP wtSEXP, SEXP deltaSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP prevresidualsSEXP, SEXP tolscaleSEXP, SEXP maxitscaleSEXP, SEXP lambdaSEXP, SEXP postSEXP, SEXP sinitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prevresiduals(prevresidualsSEXP);
    Rcpp::traits::input_parameter< double >::type tolscale(tolscaleSEXP);
    Rcpp::traits::input_parameter< int >::type maxitscale(maxitscaleSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type post(postSEXP);
    Rcpp::traits::input_parameter< double >::type sinit(sinitSEXP);
    rcpp_result_gen = Rcpp::wrap(univest_sparse(x, y, k, wt, delta, maxiter, tol, prevresiduals, tolscale, maxitscale, lambda, post, sinit));
    return rcpp_result_gen;
END_RCPP
}
// shootloop
List shootloop(arma::mat ytilde, arma::mat xtilde, arma::mat betaEst, arma::mat x, arma::mat wt, arma::vec scaleVar, double k, double delta, int maxIteration, double tol, arma::mat intercept, arma::mat Xexp, arma::vec scaleVarOLD, double tolout, double tolscale, int maxitscale, arma::mat y, int maxituniv, double wcut);
RcppExport SEXP _sparseshootS_shootloop(SEXP ytildeSEXP, SEXP xtildeSEXP, SEXP betaEstSEXP, SEXP xSEXP, SEXP wtSEXP, SEXP scaleVarSEXP, SEXP kSEXP, SEXP deltaSEXP, SEXP maxIterationSEXP, SEXP tolSEXP, SEXP interceptSEXP, SEXP XexpSEXP, SEXP scaleVarOLDSEXP, SEXP toloutSEXP, SEXP tolscaleSEXP, SEXP maxitscaleSEXP, SEXP ySEXP, SEXP maxitunivSEXP, SEXP wcutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ytilde(ytildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xtilde(xtildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type betaEst(betaEstSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scaleVar(scaleVarSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxIteration(maxIterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xexp(XexpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scaleVarOLD(scaleVarOLDSEXP);
    Rcpp::traits::input_parameter< double >::type tolout(toloutSEXP);
    Rcpp::traits::input_parameter< double >::type tolscale(tolscaleSEXP);
    Rcpp::traits::input_parameter< int >::type maxitscale(maxitscaleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxituniv(maxitunivSEXP);
    Rcpp::traits::input_parameter< double >::type wcut(wcutSEXP);
    rcpp_result_gen = Rcpp::wrap(shootloop(ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, wcut));
    return rcpp_result_gen;
END_RCPP
}
// shootloop_sparse
List shootloop_sparse(arma::mat ytilde, arma::mat xtilde, arma::mat betaEst, arma::mat x, arma::mat wt, arma::vec scaleVar, double k, double delta, int maxIteration, double tol, arma::mat intercept, arma::mat Xexp, arma::vec scaleVarOLD, double tolout, double tolscale, int maxitscale, arma::mat y, int maxituniv, double lambda, int post, double wcut);
RcppExport SEXP _sparseshootS_shootloop_sparse(SEXP ytildeSEXP, SEXP xtildeSEXP, SEXP betaEstSEXP, SEXP xSEXP, SEXP wtSEXP, SEXP scaleVarSEXP, SEXP kSEXP, SEXP deltaSEXP, SEXP maxIterationSEXP, SEXP tolSEXP, SEXP interceptSEXP, SEXP XexpSEXP, SEXP scaleVarOLDSEXP, SEXP toloutSEXP, SEXP tolscaleSEXP, SEXP maxitscaleSEXP, SEXP ySEXP, SEXP maxitunivSEXP, SEXP lambdaSEXP, SEXP postSEXP, SEXP wcutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ytilde(ytildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xtilde(xtildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type betaEst(betaEstSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scaleVar(scaleVarSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxIteration(maxIterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xexp(XexpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scaleVarOLD(scaleVarOLDSEXP);
    Rcpp::traits::input_parameter< double >::type tolout(toloutSEXP);
    Rcpp::traits::input_parameter< double >::type tolscale(tolscaleSEXP);
    Rcpp::traits::input_parameter< int >::type maxitscale(maxitscaleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxituniv(maxitunivSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type post(postSEXP);
    Rcpp::traits::input_parameter< double >::type wcut(wcutSEXP);
    rcpp_result_gen = Rcpp::wrap(shootloop_sparse(ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, lambda, post, wcut));
    return rcpp_result_gen;
END_RCPP
}
// shootloop_sparse_lambdas
List shootloop_sparse_lambdas(arma::mat ytilde, arma::mat xtilde, arma::mat betaEst, arma::mat x, arma::mat wt, arma::vec scaleVar, double k, double delta, int maxIteration, double tol, arma::mat intercept, arma::mat Xexp, arma::vec scaleVarOLD, double tolout, double tolscale, int maxitscale, arma::mat y, int maxituniv, arma::vec lambda, int post, double wcut);
RcppExport SEXP _sparseshootS_shootloop_sparse_lambdas(SEXP ytildeSEXP, SEXP xtildeSEXP, SEXP betaEstSEXP, SEXP xSEXP, SEXP wtSEXP, SEXP scaleVarSEXP, SEXP kSEXP, SEXP deltaSEXP, SEXP maxIterationSEXP, SEXP tolSEXP, SEXP interceptSEXP, SEXP XexpSEXP, SEXP scaleVarOLDSEXP, SEXP toloutSEXP, SEXP tolscaleSEXP, SEXP maxitscaleSEXP, SEXP ySEXP, SEXP maxitunivSEXP, SEXP lambdaSEXP, SEXP postSEXP, SEXP wcutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type ytilde(ytildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xtilde(xtildeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type betaEst(betaEstSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scaleVar(scaleVarSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type maxIteration(maxIterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xexp(XexpSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type scaleVarOLD(scaleVarOLDSEXP);
    Rcpp::traits::input_parameter< double >::type tolout(toloutSEXP);
    Rcpp::traits::input_parameter< double >::type tolscale(tolscaleSEXP);
    Rcpp::traits::input_parameter< int >::type maxitscale(maxitscaleSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type maxituniv(maxitunivSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type post(postSEXP);
    Rcpp::traits::input_parameter< double >::type wcut(wcutSEXP);
    rcpp_result_gen = Rcpp::wrap(shootloop_sparse_lambdas(ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, lambda, post, wcut));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sparseshootS_rhobi", (DL_FUNC) &_sparseshootS_rhobi, 2},
    {"_sparseshootS_scaleC", (DL_FUNC) &_sparseshootS_scaleC, 6},
    {"_sparseshootS_wbi", (DL_FUNC) &_sparseshootS_wbi, 2},
    {"_sparseshootS_sign", (DL_FUNC) &_sparseshootS_sign, 1},
    {"_sparseshootS_betawls", (DL_FUNC) &_sparseshootS_betawls, 3},
    {"_sparseshootS_univest", (DL_FUNC) &_sparseshootS_univest, 11},
    {"_sparseshootS_univest_sparse", (DL_FUNC) &_sparseshootS_univest_sparse, 13},
    {"_sparseshootS_shootloop", (DL_FUNC) &_sparseshootS_shootloop, 19},
    {"_sparseshootS_shootloop_sparse", (DL_FUNC) &_sparseshootS_shootloop_sparse, 21},
    {"_sparseshootS_shootloop_sparse_lambdas", (DL_FUNC) &_sparseshootS_shootloop_sparse_lambdas, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_sparseshootS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
