# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rhobi <- function(z, k) {
    .Call(`_sparseshootS_rhobi`, z, k)
}

scaleC <- function(u, kp, cc, initialsc, maxit, tol) {
    .Call(`_sparseshootS_scaleC`, u, kp, cc, initialsc, maxit, tol)
}

wbi <- function(z, k) {
    .Call(`_sparseshootS_wbi`, z, k)
}

sign <- function(x) {
    .Call(`_sparseshootS_sign`, x)
}

betawls <- function(X, Y, W) {
    .Call(`_sparseshootS_betawls`, X, Y, W)
}

univest <- function(x, y, k, wt, delta, maxiter, tol, prevresiduals, tolscale, maxitscale, sinit) {
    .Call(`_sparseshootS_univest`, x, y, k, wt, delta, maxiter, tol, prevresiduals, tolscale, maxitscale, sinit)
}

univest_sparse <- function(x, y, k, wt, delta, maxiter, tol, prevresiduals, tolscale, maxitscale, lambda, post, sinit) {
    .Call(`_sparseshootS_univest_sparse`, x, y, k, wt, delta, maxiter, tol, prevresiduals, tolscale, maxitscale, lambda, post, sinit)
}

shootloop <- function(ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, wcut) {
    .Call(`_sparseshootS_shootloop`, ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, wcut)
}

shootloop_sparse <- function(ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, lambda, post, wcut) {
    .Call(`_sparseshootS_shootloop_sparse`, ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, lambda, post, wcut)
}

shootloop_sparse_lambdas <- function(ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, lambda, post, wcut) {
    .Call(`_sparseshootS_shootloop_sparse_lambdas`, ytilde, xtilde, betaEst, x, wt, scaleVar, k, delta, maxIteration, tol, intercept, Xexp, scaleVarOLD, tolout, tolscale, maxitscale, y, maxituniv, lambda, post, wcut)
}

